### ISSUE TITLE
Fix entro PyPi module.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/entro.py#7]
**Overview of this Issue**

Currently, once entropy is installed, it must be imported using 'import entro.entro'. This doesn't make sense. It can be fixed by moving the module into the root folder.

**Tasks to Close Issue**

- [x] Move entro.py to the root folder.
- [x] Update setup.py
- [x] Create new release.
- [x] Update PyPi release.

**Comment by mikesiers** [comment]
http://pypi.python.org/pypi/entro
